export const UPDATE_SHOWING_ERROR = 'APP/UPDATE_SHOWING_ERROR'
export const UPDATE_SHOW_LOADER = 'APP/UPDATE_SHOW_LOADER'
export const SHOW_ACTION_POPUP = 'APP/SHOW_ACTION_POPUP'
export const HIDE_ACTION_POPUP = 'APP/HIDE_ACTION_POPUP'
export const SHOW_ACTION_FORM = 'APP/SHOW_ACTION_FORM'
export const HIDE_ACTION_FORM = 'APP/HIDE_ACTION_FORM'

const CHANNEL_TYPES = {
    AUDIO_IN: 0,
    AUDIO_OUT: 1,
    EVENTS: 2
}
export { CHANNEL_TYPES }
